version: '3.8'

services:

  backend:
    container_name: Winfrey-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: winfrey-backend-ip
    ports:
      - "5000:5000"
    env_file: 
      - ./backend/.env
    networks:
      - Muiruri-net
    

  client:
    container_name: Winfrey-client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: winfrey-client-ip
    ports:
     - "3000:80" 
    depends_on: 
      - backend
    networks:
      - Muiruri-net
    


networks:
  Muiruri-net:
    driver: bridge



