version: '3.8'

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - Muiruri-net

  backend:
    container_name: Winfrey-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
    networks:
      - Muiruri-net
    working_dir: /app
    command: npm start

  client:
    container_name: Winfrey-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on: 
      - backend
    networks:
      - Muiruri-net
    volumes:
      - ./client:/app 
    working_dir: /app
    command: npm start
    stdin_open: true
    tty: true

networks:
  Muiruri-net:
    driver: bridge

volumes:
  mongo-data:

