---
- name: Ansible playbook to automate deployment of the Yolo e-commerce app
  hosts: all
  become: true

  vars_files:
    - vars/vars.yml    # Load variables from vars file

  roles:
    - role: docker                  # Installs Docker and Docker Compose
      tags: docker

    - role: setup-mongodb            # Sets up MongoDB container
      tags: mongo

    - role: frontend-deployment     # Clones app and runs frontend container
      tags: frontend

    - role: backend-deployment      # Clones app and runs backend container
      tags: backend

    