---
- name: Ansible playbook to automate deployment of the Yolo e-commerce app
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars/vars.yml

  pre_tasks:
    - name: Ensure Docker network exists
      community.docker.docker_network:
        name: app-net
        state: present

  roles:
    - role: docker
      tags: docker

    - role: setup-mongodb
      tags: mongo

    - role: frontend-deployment
      tags: frontend

    - role: backend-deployment
      tags: backend

