---
- name: Run MongoDB Container
  community.docker.docker_container:
    name: app-mongo
    image: "{{ mongo_image }}"
    ports:
      - "{{ mongo_port }}"
    volumes:
      - ./app-mongo-data:/data/db
    networks:
      - name: "{{ docker_network }}"
  tags:
    - database
    - backend

