- name: Create backend container on custom network
  community.docker.docker_container:
    name: yolo-backend
    image: winfr3y/backend:latest
    state: started
    restart_policy: always
    networks:
      - name: app-net
    ports:
      - "5008:5000"
    env:
      MONGODB_URI: "mongodb://yolo-mongo:27017/yolodb"

